---@type Adan.LspRegistry
return {
  bashls = true,
  clangd = true,
  -- cmake = true,
  gleam = true,
  gopls = true,
  harper_ls = false,
  lua_ls = true,
  markdown_oxide = true,
  jade_toml = false,
  nixd = true,
  neocmake = true,
  ocamllsp = false,
  powershell_es = true,
  pyrefly = false,
  ruff = true,
  rust_analyzer = true,
  texlab = true,
  tombi = true,
  ts_ls = true,
  ty = true,
  yamlls = true,
  zls = true,
  ols = true,
  lemminx = true,
}
