---@type vim.lsp.Config
return {
  cmd = { 'ruff', 'server', '--preview' },
  filetypes = { 'python' },

  root_markers = {
    'pyproject.toml',
    'pyrightconfig.json',
    'ruff.toml',
    '.ruff.toml',
    'setup.py',
    'setup.cfg',
    'requirements.txt',
    'Pipfile',
    '.git',
  },
  settings = {
    exclude = {
      '.bzr',
      '.direnv',
      '.eggs',
      '.git',
      '.git-rewrite',
      '.hg',
      '.ipynb_checkpoints',
      '.mypy_cache',
      '.nox',
      '.pants.d',
      '.pyenv',
      '.pytest_cache',
      '.pytype',
      '.ruff_cache',
      '.svn',
      '.tox',
      '.venv',
      '.vscode',
      '__pypackages__',
      '_build',
      'buck-out',
      'build',
      'dist',
      'node_modules',
      'site-packages',
      'venv',
    },
    ['indent-width'] = 4,
    ['line-length'] = 120,
    ['target-version'] = 'py311',
    format = {
      ['indent-style'] = 'space',
      ['line-ending'] = 'auto',
      preview = true,
      ['quote-style'] = 'single',
      ['skip-magic-trailing-comma'] = false,
    },
    lint = {
      fixable = { 'ALL' },
      ignore = { 'E501', 'F403', 'F405' },
      preview = true,
      select = { 'E4', 'E7', 'E9', 'F', 'B' },
      unfixable = { 'B' },
    },
  },
}
